# Generated by Django 3.1.3 on 2020-11-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=250)),
                ('CountryCode', models.CharField(max_length=250)),
                ('Slug', models.CharField(max_length=10)),
                ('NewConfirmed', models.IntegerField()),
                ('TotalConfirmed', models.IntegerField()),
                ('NewDeaths', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('NewRecovered', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'covid19',
                'verbose_name_plural': 'covid19',
            },
        ),
    ]
