# Generated by Django 3.1.3 on 2020-11-05 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('countryCode', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=10)),
                ('newConfirmed', models.IntegerField()),
                ('totalConfirmed', models.IntegerField()),
                ('newDeaths', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('newRecovered', models.IntegerField()),
                ('totalRecovered', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'covid19',
                'verbose_name_plural': 'covid19',
            },
        ),
    ]
